### ISSUE TITLE
Nested recursion malfunctions

### ISSUE THREAD

**Issue by LightAndLight** [LightAndLight/typed-cfg#7]
It seems like names are getting mixed up somewhere in nested recursion.

```
-- |
-- T ::= e | '(' U ')' T
-- U ::= e | '{' T '}' U
alternate :: CFG () v Char ()
alternate =
  Mu () $ \t ->
  Or ()
    (Empty ())
    (Char () '(' .>
     (Mu () $ \u ->
      Or ()
        (Empty ())
        (Char () '{' .> Var () t <. Char () '}' <. Var () u)) <.
     Char () ')' <.
     Var () t)
```

```
*CFG Test> parseAlternate "({{}})"
Just ("",())
*CFG Test> parseAlternate "({()})"
Nothing
```

You can also see it in the generated core- `x` should have a call back to `parseAlternate`, not `x`
![GHC core output](https://i.imgur.com/hcoxSP2.png)

**Comment by mpickering** [comment]
Probably a problem with the wrong index being used to index into the context?

**Comment by LightAndLight** [comment]
I think it's probably name shadowing in the Mu case.

**Comment by LightAndLight** [comment]
You're right, the variables are added to the context in the wrong order.
